version: "3.8"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ../log-analysis-system-api/LogAnalysisApi
      dockerfile: Dockerfile
    ports:
      - "5044:80"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:9.2
    container_name: vue-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pawel
      MYSQL_DATABASE: pawel
      MYSQL_USER: pawel
      MYSQL_PASSWORD: pawel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

